/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OfertalancamentoRouteImport } from './routes/ofertalancamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCalendarRouteImport } from './routes/api/calendar'
import { Route as ApiAiScanRouteImport } from './routes/api/ai-scan'
import { Route as ApiAiMindRouteImport } from './routes/api/ai-mind'
import { Route as AppUpgradeRouteImport } from './routes/_app/upgrade'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppNoticiasRouteImport } from './routes/_app/noticias'
import { Route as AppMindRouteImport } from './routes/_app/mind'
import { Route as AppGestaoRouteImport } from './routes/_app/gestao'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCryptobubblesRouteImport } from './routes/_app/cryptobubbles'
import { Route as AppCalculadoraRouteImport } from './routes/_app/calculadora'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertalancamentoRoute = OfertalancamentoRouteImport.update({
  id: '/ofertalancamento',
  path: '/ofertalancamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScanRoute = ApiAiScanRouteImport.update({
  id: '/api/ai-scan',
  path: '/api/ai-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMindRoute = ApiAiMindRouteImport.update({
  id: '/api/ai-mind',
  path: '/api/ai-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticiasRoute = AppNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AppRoute,
} as any)
const AppMindRoute = AppMindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCryptobubblesRoute = AppCryptobubblesRouteImport.update({
  id: '/cryptobubbles',
  path: '/cryptobubbles',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculadoraRoute = AppCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ofertalancamento': typeof OfertalancamentoRoute
  '/signup': typeof SignupRoute
  '/calculadora': typeof AppCalculadoraRoute
  '/cryptobubbles': typeof AppCryptobubblesRoute
  '/dashboard': typeof AppDashboardRoute
  '/gestao': typeof AppGestaoRoute
  '/mind': typeof AppMindRoute
  '/noticias': typeof AppNoticiasRoute
  '/perfil': typeof AppPerfilRoute
  '/scan': typeof AppScanRoute
  '/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ofertalancamento': typeof OfertalancamentoRoute
  '/signup': typeof SignupRoute
  '/calculadora': typeof AppCalculadoraRoute
  '/cryptobubbles': typeof AppCryptobubblesRoute
  '/dashboard': typeof AppDashboardRoute
  '/gestao': typeof AppGestaoRoute
  '/mind': typeof AppMindRoute
  '/noticias': typeof AppNoticiasRoute
  '/perfil': typeof AppPerfilRoute
  '/scan': typeof AppScanRoute
  '/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/ofertalancamento': typeof OfertalancamentoRoute
  '/signup': typeof SignupRoute
  '/_app/calculadora': typeof AppCalculadoraRoute
  '/_app/cryptobubbles': typeof AppCryptobubblesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/mind': typeof AppMindRoute
  '/_app/noticias': typeof AppNoticiasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
  '/api/calendar': typeof ApiCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/ofertalancamento'
    | '/signup'
    | '/calculadora'
    | '/cryptobubbles'
    | '/dashboard'
    | '/gestao'
    | '/mind'
    | '/noticias'
    | '/perfil'
    | '/scan'
    | '/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
    | '/api/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/ofertalancamento'
    | '/signup'
    | '/calculadora'
    | '/cryptobubbles'
    | '/dashboard'
    | '/gestao'
    | '/mind'
    | '/noticias'
    | '/perfil'
    | '/scan'
    | '/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
    | '/api/calendar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/ofertalancamento'
    | '/signup'
    | '/_app/calculadora'
    | '/_app/cryptobubbles'
    | '/_app/dashboard'
    | '/_app/gestao'
    | '/_app/mind'
    | '/_app/noticias'
    | '/_app/perfil'
    | '/_app/scan'
    | '/_app/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
    | '/api/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OfertalancamentoRoute: typeof OfertalancamentoRoute
  SignupRoute: typeof SignupRoute
  ApiAiMindRoute: typeof ApiAiMindRoute
  ApiAiScanRoute: typeof ApiAiScanRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertalancamento': {
      id: '/ofertalancamento'
      path: '/ofertalancamento'
      fullPath: '/ofertalancamento'
      preLoaderRoute: typeof OfertalancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-scan': {
      id: '/api/ai-scan'
      path: '/api/ai-scan'
      fullPath: '/api/ai-scan'
      preLoaderRoute: typeof ApiAiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-mind': {
      id: '/api/ai-mind'
      path: '/api/ai-mind'
      fullPath: '/api/ai-mind'
      preLoaderRoute: typeof ApiAiMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/noticias': {
      id: '/_app/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AppNoticiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mind': {
      id: '/_app/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof AppMindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cryptobubbles': {
      id: '/_app/cryptobubbles'
      path: '/cryptobubbles'
      fullPath: '/cryptobubbles'
      preLoaderRoute: typeof AppCryptobubblesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculadora': {
      id: '/_app/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AppCalculadoraRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalculadoraRoute: typeof AppCalculadoraRoute
  AppCryptobubblesRoute: typeof AppCryptobubblesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGestaoRoute: typeof AppGestaoRoute
  AppMindRoute: typeof AppMindRoute
  AppNoticiasRoute: typeof AppNoticiasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppScanRoute: typeof AppScanRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalculadoraRoute: AppCalculadoraRoute,
  AppCryptobubblesRoute: AppCryptobubblesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGestaoRoute: AppGestaoRoute,
  AppMindRoute: AppMindRoute,
  AppNoticiasRoute: AppNoticiasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppScanRoute: AppScanRoute,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OfertalancamentoRoute: OfertalancamentoRoute,
  SignupRoute: SignupRoute,
  ApiAiMindRoute: ApiAiMindRoute,
  ApiAiScanRoute: ApiAiScanRoute,
  ApiCalendarRoute: ApiCalendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
