/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiScanRouteImport } from './routes/api/ai-scan'
import { Route as ApiAiMindRouteImport } from './routes/api/ai-mind'
import { Route as AppUpgradeRouteImport } from './routes/_app/upgrade'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppMindRouteImport } from './routes/_app/mind'
import { Route as AppGestaoRouteImport } from './routes/_app/gestao'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScanRoute = ApiAiScanRouteImport.update({
  id: '/api/ai-scan',
  path: '/api/ai-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMindRoute = ApiAiMindRouteImport.update({
  id: '/api/ai-mind',
  path: '/api/ai-mind',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppMindRoute = AppMindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gestao': typeof AppGestaoRoute
  '/mind': typeof AppMindRoute
  '/scan': typeof AppScanRoute
  '/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gestao': typeof AppGestaoRoute
  '/mind': typeof AppMindRoute
  '/scan': typeof AppScanRoute
  '/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/mind': typeof AppMindRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/api/ai-mind': typeof ApiAiMindRoute
  '/api/ai-scan': typeof ApiAiScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/gestao'
    | '/mind'
    | '/scan'
    | '/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/gestao'
    | '/mind'
    | '/scan'
    | '/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/gestao'
    | '/_app/mind'
    | '/_app/scan'
    | '/_app/upgrade'
    | '/api/ai-mind'
    | '/api/ai-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAiMindRoute: typeof ApiAiMindRoute
  ApiAiScanRoute: typeof ApiAiScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-scan': {
      id: '/api/ai-scan'
      path: '/api/ai-scan'
      fullPath: '/api/ai-scan'
      preLoaderRoute: typeof ApiAiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-mind': {
      id: '/api/ai-mind'
      path: '/api/ai-mind'
      fullPath: '/api/ai-mind'
      preLoaderRoute: typeof ApiAiMindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mind': {
      id: '/_app/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof AppMindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGestaoRoute: typeof AppGestaoRoute
  AppMindRoute: typeof AppMindRoute
  AppScanRoute: typeof AppScanRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGestaoRoute: AppGestaoRoute,
  AppMindRoute: AppMindRoute,
  AppScanRoute: AppScanRoute,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAiMindRoute: ApiAiMindRoute,
  ApiAiScanRoute: ApiAiScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
