// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccjfmgfyndyhvfqbceed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjamZtZ2Z5bmR5aHZmcWJjZWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1NTk4ODUsImV4cCI6MjA5NDEzNTg4NX0.gd9YKLFR41JYA1XGkRQ-nWRdl74oD6wAt7kFXu7i1nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});